
FROM ubuntu:latest

RUN apt-get update && apt-get install -y openssh-client netcat-traditional

RUN ssh-keygen -t rsa -b 2048 -f /root/.ssh/id_rsa -N '' && cat /root/.ssh/id_rsa.pub
ENTRYPOINT ["/bin/bash"]
