version: '3'
services:
  attacker:
    build:
      context: .
      dockerfile: Dockerfile_attacker
    container_name: attacker_container
    hostname: attacker
    networks:
      - my_network
    ports:
      - "1234:1234"  
    volumes:
      - ./code:/code  
    tty: true
    stdin_open: true  

  victim:
    build:
      context: .
      dockerfile: Dockerfile_victim
    container_name: victim_container
    hostname: victim
    networks:
      - my_network
    volumes:
      - ./code:/code  
    ports:
      - "2223:22"
networks:
  my_network:
    driver: bridge
